### ISSUE TITLE
make parameters and attributes anchors in docstrings

### ISSUE THREAD

**Issue by amueller** [numpy/numpydoc#185] opened 2018-07-12 18:40 UTC
Somewhere there was a mention, I think by @jnothman to make parameters and attributes in the docstring anchors so we can link to them from within the docstring (often attributes refer to parameters or parameters to other parameters in scikit-learn)

**Comment by rgommers** [comment] 2018-07-12 20:55
duplicate of gh-88 I believe (although it talks about sections rather than parameters/attributers). can you weigh in there?

**Closed by rgommers** 2018-07-12 20:55 UTC
