### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by jnothman** [numpy/numpydoc#89] opened 2017-03-12 23:30 UTC
It's been over a year since the last release. I would like to use recent changes in scikit-learn, and it looks like numpy too is being built on the latest release, not on master. Could we more generally plan half-yearly releases or something, even if they're quite small?

**Comment by rgommers** [comment] 2017-03-13 08:08
Yes, good idea. I thought we had released 0.7.0 a few months ago, but apparently not. IIRC we need to resolve the duplicate sections issue still.

I can make some time to do this release.

**Comment by jnothman** [comment] 2017-03-13 09:32
Great, thanks!

**Comment by pv** [comment] 2017-05-05 19:00
I guess scipy docs don't build with the current master --- would need to check if the issue is here or elsewhere.

**Comment by jschueller** [comment] 2017-05-12 07:00
@pv hi, I think I found a possible regression (https://github.com/numpy/numpydoc/pull/93), maybe it's that problem preventing you from compiling scipy ?

**Comment by jschueller** [comment] 2017-05-12 07:03
Also, about the release, latest numpydoc release 0.6 cannot be used with sphinx git anymore as they removed some compatibility module, so I guess the next sphinx release will need a numpydoc release too.

**Comment by amueller** [comment] 2017-05-18 19:28
Lol I was just about to open it, @jnothman beat me to it, of course.
What's the status? Is #93 blocking? Scipy build blocking? Would be cool to have a list.

**Comment by amueller** [comment] 2017-05-18 19:29
Also: the current github master identifies itself as 0.6.0, which is not ideal.

**Comment by jschueller** [comment] 2017-05-18 19:42
@amueller I incremented the version number to 0.7.0 in #94

**Comment by rgommers** [comment] 2017-06-18 11:09
> What's the status? Is #93 blocking? Scipy build blocking? Would be cool to have a list.

Last time I checked the Scipy docs built fine - will check again. AFAICS the one thing that needs resolving is gh-67.

**Comment by rgommers** [comment] 2017-06-18 11:26
Current numpydoc master + scipy master builds fine.

**Comment by amueller** [comment] 2017-06-18 16:21
I have some weird issues in scikit-learn that I don't understand. Any help with that would be much appreciated: https://github.com/sphinx-doc/sphinx/issues/3768#issuecomment-303839520
It only happens with the numpydoc update, so maybe it's actually a numpydoc error. I'll open an issue here - I have no idea what's going on.

**Comment by rgommers** [comment] 2017-06-19 10:02
> I have some weird issues in scikit-learn that I don't understand. Any help with that would be much appreciated: sphinx-doc/sphinx#3768 (comment)

For future reference: this was fixed by gh-93.

**Comment by amueller** [comment] 2017-06-19 14:34
Also, now I'd be very happy with a release of the current state, because scikit-learn builds fine!

**Comment by rgommers** [comment] 2017-06-20 09:30
> Also, now I'd be very happy with a release of the current state,

I think I'll work on that right now, before life interferes again:) gh-67 has a merge conflict and an un-addressed review comment, so we can always cut another release later (not too much work).

**Comment by rgommers** [comment] 2017-06-20 10:36
Okay, done: https://pypi.python.org/pypi/numpydoc/0.7.0

Somehow the readme went missing, looked into that but no luck - opened https://github.com/pypa/pypi-legacy/issues/653

**Closed** 2017-06-20 10:36 UTC

**Comment by pv** [comment] 2017-06-20 10:50
Pypi doesn't look inside the tarball or any readme files.
.
The description is whathever is in the longdescription="" parameter for 
setup.py. Here, we don't have anything there.

**Comment by pv** [comment] 2017-06-20 10:51
The description could previously be edited on the Pypi web interface.
That's probably no longer the case.

**Comment by rgommers** [comment] 2017-06-20 11:18
Thanks @pv. Can't remember doing that last time around, but that's probably old age. Fixed now.

**Comment by amueller** [comment] 2017-06-20 14:02
Amazing!
Thank you!

**Comment by amueller** [comment] 2017-06-20 14:06
Amazing!
Thank you!

Sent from phone. Please excuse spelling and brevity.

On Jun 20, 2017 07:18, "Ralf Gommers" <notifications@github.com> wrote:

Thanks @pv <https://github.com/pv>. Can't remember doing that last time
around, but that's probably old age. Fixed now.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/numpy/numpydoc/issues/89#issuecomment-309722759>, or mute
the thread
