### ISSUE TITLE
Unknown Section error has no context.

### ISSUE THREAD

**Issue by amueller** [numpy/numpydoc#99] opened 2017-06-18 20:24 UTC
Similar to #95 the "Unknown section: X" error has no context, making it really hard to find and fix :-/

**Comment by amueller** [comment] 2017-06-18 20:24
(Say someone used ``Note`` instead of ``Notes``, a ``git grep Note`` is not very helpful in a large codebase)

**Comment by jnothman** [comment] 2017-09-10 13:01
This is a duplicate of #10, btw.

**Closed** 2017-09-17 04:18 UTC
Labels: bug
